# Nome do workflow que aparece na aba "Actions" do GitHub
name: CI/CD Pipeline

#Quando executar: a cada push ou pull request na branch main
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 

# Lista de jobs a serem executados
jobs:
  ci:
    # Sistema operacional onde o job será executado
    runs-on: ubuntu-latest

    # Lista de passos a serem executados no job
    steps:
     # Passo 1: Clonar o repositório
     - name: Fazer checkout do código
       uses: actions/checkout@v4
    
    # Passo 2: Configurar o Java 21
     - name: Configurar Java 21
       uses: actions/setup-java@v3
       with:
        java-version: '21'

    # Passo 3: Executar testes
     - name: Executar testes 
       run: mvn -B test --file pom.xml